name: Python Security Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit

    - name: Run Bandit
      run: |
        bandit -r . -f json > bandit-output.json

    - name: Upload Bandit report
      uses: actions/upload-artifact@v2
      with:
        name: Bandit report
        path: bandit-output.json
