name: Bandit Scan

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create output directory
        run: mkdir -p output

      - name: Security check - Bandit
        uses: ioggstream/bandit-report-artifacts@v0.0.2
        with:
          project_path: .
          ignore_failure: true
          output_format: json  # Specify the output format as JSON

      - name: Save security report
        run: |
          echo -n "${{ steps.bandit.outputs.report }}" > output/security_report.json

      - name: Display security report
        run: cat output/security_report.json

      - name: Check for security risks
        run: |
          if grep -q "HIGH" output/security_report.json; then
            echo "Security risks found. Blocking PR. Artifact: ${{ github.server_url }}/${{ github.repository }}/actions/artifacts/$(< output/security_report.json)"
            exit 1
          fi

      - name: Upload security report artifact
        uses: actions/upload-artifact@v2
        with:
          name: Security report
          path: output/security_report.json
