name: Security Check

on:
  push:
  workflow_dispatch:

jobs:
  Bandit:
    name: Bandit Scan
    needs: owasp_dependency_check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Security check - Bandit
        uses: ioggstream/bandit-report-artifacts@v0.0.2
        with:
          project_path: .
          ignore_failure: true

      - name: Security check report artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Security report
          path: output/security_report.txt

      - name: Check for security risks
        run: |
          if grep -q "HIGH" output/security_report.txt; then
            echo "Security risks found. Blocking push."
            exit 1
          else
            echo "No security risks found."
            exit 0
          fi

      - name: Generate JSON output
        run: |
          cat output/security_report.txt | jq .
