name: Ban

on:
  push:
    branches:
      - master

jobs:
  Bandit:
    name: Bandit Scan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit
          pip install tabulate

      - name: Security check - Bandit
        run: |
          bandit -r . > bandit_report.txt || true

      - name: Parse Bandit report
        run: |
          import re
          import textwrap
          import json
          from tabulate import tabulate

          # Read the Bandit report file
          with open('bandit_report.txt', 'r') as file:
              file_contents = file.read()

          # Regex pattern to capture the required information
          pattern = r'Issue: (.*?)\n.*?Severity: (.*?)\n.*?CWE: (.*?)\n.*?Location: (.*?)\n'
          matches = re.findall(pattern, file_contents, re.DOTALL)

          # Format the matches into table rows
          table_rows = []
          for match in matches:
              issue = textwrap.fill(match[0], width=30)
              severity = match[1].split()[0]
              cwe = textwrap.fill(match[2], width=30)
              location = match[3].strip()
              table_rows.append([issue, severity, cwe, location])

          # Custom sort function
          severity_order = {'High': 0, 'Medium': 1, 'Low': 2}

          # Sort the rows
          sorted_rows = sorted(table_rows, key=lambda x: severity_order[x[1]])

          # Specify the table headers
          table_headers = ["Issue", "Severity", "CWE", "Location"]

          # Print the table
          print(tabulate(sorted_rows, headers=table_headers, tablefmt='grid'))

        shell: python
