name: Bandit Scan

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Security check - Bandit
        uses: ioggstream/bandit-report-artifacts@v0.0.2
        with:
          project_path: .
          ignore_failure: true
          output_format: json  # Specify the output format as JSON

      - name: Save security report
        run: echo "${{ steps.bandit.outputs.report }}" > output/security_report.json

      - name: Display security report
        run: cat output/security_report.json

      - name: Upload security report artifact
        uses: actions/upload-artifact@v2
        with:
          name: Security report
          path: output/security_report.json
