name: Bandit Scan

on:
  push:
    branches: master

jobs:
  bandit:
    name: Bandit Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit
          pip install jq

      - name: Run Bandit
        id: bandit
        run: |
          bandit -r . -ll -f json -o bandit_report.json || echo "::set-output name=bandit_failed::true"
          pwd
          cat bandit_report.json 

     
         
