name: Security check - Bandit CSNA

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Python security check using Bandit CSNA and output as JSON
        uses: kmcquade/bandit-report-artifacts-json@0.0.1
        with:
          python_version: 3.8.10
          project_path: .
          ignore_failure: false

      - name: Security check report artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Security report
          path: output/.
