name: Bandit Scan

on:
  push:
    branches: master

jobs:
  bandit:
    name: Bandit Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit
          pip install jq
      - name: Run Bandit
        id: bandit
        run: |
          bandit -r . -ll -o bandit_report.json | jq .

      - name: Check Bandit status
        if: ${{ steps.bandit.outputs.bandit_failed == 'true' }}
        run: |
          echo "Bandit found vulnerabilities."

      - name: Store Bandit report
        if: ${{ steps.bandit.outputs.bandit_failed == 'true' }}
        run: |
          echo "Storing Bandit report."
          echo "${{ steps.bandit.outputs.bandit_report }}" > bandit_report.json
