name: Secret Scan

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  security_scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install TruffleHog and Dependencies
        run: |
          sudo apt-get install -y python3 python3-pip
          pip install trufflehog

      - name: Run TruffleHog Scan
        run: |
          bash -c "trufflehog --entropy=True --json ${{ github.workspace }} > trufflehog_report.json"

      - name: Display TruffleHog Secrets
        run: |
          if [ -s trufflehog_report.json ]; then
            echo "TruffleHog Secrets found:"
            cat trufflehog_report.json
          else
            echo "No TruffleHog secrets found."
          fi

      - name: Upload TruffleHog Report
        uses: actions/upload-artifact@v2
        with:
          name: trufflehog-report
          path: trufflehog_report.json
