name: Harden Runner

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Harden Runner
        uses: step-security/harden-runner@v2.4.1

      - name: Archive Harden Runner output
        uses: actions/upload-artifact@v2
        with:
          name: harden-runner-output
          path: output-folder
