name: Check

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  security_scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get install -y diffutils jq python3 python3-pip
          pip install trufflehog
          pip install detect-secrets

      - name: Verify Trufflehog Installation
        run: trufflehog --version

      - name: Run Trufflehog Scan
        run: |
          trufflehog --entropy=True --json ${{ github.workspace }} > secret_scan_trufflehog.json || exit 0

      - name: Display Trufflehog Secrets
        run: |
          if [ -s secret_scan_trufflehog.json ]; then
            echo "Trufflehog Secrets found:"
            cat secret_scan_trufflehog.json
          else
            echo "No Trufflehog secrets found."
          fi

      - name: Run Detect Secrets Scan
        run: |
          detect-secrets scan --baseline .secrets.new "$(find ${{ github.workspace }} -type f ! -name '.secrets.*' ! -path '*/.git*')" > secret_scan_detect_secrets.json

      - name: Display Detect Secrets
        run: |
          if [ -s secret_scan_detect_secrets.json ]; then
            echo "Detect-secrets Secrets found:"
            cat secret_scan_detect_secrets.json
          else
            echo "No Detect-secrets secrets found."
          fi

      - name: Combine and Display Unique Secrets
        run: |
          combined_output=$(cat secret_scan_trufflehog.json secret_scan_detect_secrets.json | jq -s '. | unique | sort')
          if [ "$combined_output" != "[]" ]; then
            echo "Combined Unique Secrets (sorted):"
            echo "$combined_output"
          else
            echo "No combined secrets found."
          fi
