name: testscan

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  security_scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get install -y diffutils jq python3 python3-pip
          pip install detect-secrets

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.44.0
        with:
          path: ${{ github.workspace }}

      - name: Display TruffleHog Secrets
        run: |
          if [ -s trufflehog_report.json ]; then
            echo "TruffleHog Secrets found:"
            cat trufflehog_report.json
          else
            echo "No TruffleHog secrets found."
          fi

      - name: Run Detect Secrets Scan
        run: |
          detect-secrets scan --baseline .secrets.new "$(find ${{ github.workspace }} -type f ! -name '.secrets.*' ! -path '*/.git*')" > secret_scan_detect_secrets.json

      - name: Display Detect Secrets
        run: |
          if [ -s secret_scan_detect_secrets.json ]; then
            echo "Detect-secrets Secrets found:"
            cat secret_scan_detect_secrets.json
          else
            echo "No Detect-secrets secrets found."
          fi

      - name: Combine and Display Unique Secrets
        run: |
          combined_output=$(cat trufflehog_report.json secret_scan_detect_secrets.json | jq -s '. | unique | sort')
          if [ "$combined_output" != "[]" ]; then
            echo "Combined Unique Secrets (sorted):"
            echo "$combined_output"
          else
            echo "No combined secrets found."
          fi
