name: Bandit Scan

on: 
  push:
    branches:
      - master

jobs:
  Bandit:
    name: Bandit Scan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Security check - Bandit
        run: |
          bandit -r . > bandit_report.txt || true
          
      - name: Upload Bandit report
        uses: actions/upload-artifact@v2
        with:
          name: bandit_report
          path: bandit_report.txt
