name: Secret Scanning

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  secret_scanning:
    name: Secret Scanning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.41.1


      - name: Run TruffleHog scan
        if: ${{ always() }}
        run: |
          mkdir -p findings
          sh -c 'trufflehog --regex --entropy=False . > findings/trufflehog_report.txt'
        continue-on-error: true
        env:
          ARTIFACTS_DIR: ${{ github.workspace }}/findings

      - name: Upload findings as artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: TruffleHog Findings
          path: ${{ env.ARTIFACTS_DIR }}
