name: "CodeQL"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '45 18 * * 4'

jobs:
  secret_scanning:
    name: Secret Scanning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install TruffleHog
        run: pip install trufflehog

      - name: Run TruffleHog scan
        run: trufflehog --regex --entropy=False .

      - name: Save TruffleHog output to file
        id: save_output
        run: |
          trufflehog --regex --entropy=False . > trufflehog_output.txt
          echo "::set-output name=filename::trufflehog_output.txt"

      - name: Upload TruffleHog output as artifact
        uses: actions/upload-artifact@v2
        with:
          name: trufflehog-output
          path: trufflehog_output.txt
