name: Detect Secrets

on:
  push:
    branches:
      - main, master
  pull_request:
    branches:
      - main, master

jobs:
  validate_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3

      - name: Install dependencies
        run: pip install detect-secrets

      - name: Run detect-secrets tool
        run: detect-secrets scan --all-files --exclude-files FETCH_HEAD > detect-secrets.json

      - name: Verify Secrets
        run: |
          dsjson=$(cat detect-secrets.json)
          echo "${dsjson}"

          count=$(echo "${dsjson}" | jq -c -r '.results | length')

          if [ $count -gt 0 ]; then
            echo "Error: Secrets were detected in code. ${count} file(s) affected."
            exit 1
          else
            echo "No secrets detected."
          fi
